[build]
  publish = "frontend"
  # This tells Netlify where your serverless functions are located
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
